-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 02:38:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Funcionalitester
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Funcionalitester` ;

-- -----------------------------------------------------
-- Schema Funcionalitester
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Funcionalitester` DEFAULT CHARACTER SET utf8 ;
USE `Funcionalitester` ;

-- -----------------------------------------------------
-- Table `Funcionalitester`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionalitester`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `Funcionalitester`.`Pessoa` (
  `id_Pessoa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(45) NULL,
  `atribuicoes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionalitester`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionalitester`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Funcionalitester`.`Usuario` (
  `Pessoa_idPessoa` INT NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Linguagem` VARCHAR(45) NULL,
  PRIMARY KEY (`Pessoa_idPessoa`),
  CONSTRAINT `fk_Usuario_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `Funcionalitester`.`Pessoa` (`id_Pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionalitester`.`Software`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionalitester`.`Software` ;

CREATE TABLE IF NOT EXISTS `Funcionalitester`.`Software` (
  `idSoftware` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataCriacao` VARCHAR(45) NULL,
  `Dono` VARCHAR(45) NOT NULL,
  `Equipe` VARCHAR(45) NULL,
  `Usuario_Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idSoftware`, `Usuario_Pessoa_idPessoa`),
  INDEX `fk_Software_Usuario1_idx` (`Usuario_Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Software_Usuario1`
    FOREIGN KEY (`Usuario_Pessoa_idPessoa`)
    REFERENCES `Funcionalitester`.`Usuario` (`Pessoa_idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionalitester`.`Funcionalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionalitester`.`Funcionalidade` ;

CREATE TABLE IF NOT EXISTS `Funcionalitester`.`Funcionalidade` (
  `idFuncionalidade` INT NOT NULL AUTO_INCREMENT,
  `Funcao` VARCHAR(45) NOT NULL,
  `Usuario_Pessoa_idPessoa` INT NOT NULL,
  `Software_idSoftware` INT NOT NULL,
  PRIMARY KEY (`idFuncionalidade`, `Usuario_Pessoa_idPessoa`, `Software_idSoftware`),
  INDEX `fk_Funcionalidade_Usuario1_idx` (`Usuario_Pessoa_idPessoa` ASC),
  INDEX `fk_Funcionalidade_Software1_idx` (`Software_idSoftware` ASC),
  CONSTRAINT `fk_Funcionalidade_Usuario1`
    FOREIGN KEY (`Usuario_Pessoa_idPessoa`)
    REFERENCES `Funcionalitester`.`Usuario` (`Pessoa_idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionalidade_Software1`
    FOREIGN KEY (`Software_idSoftware`)
    REFERENCES `Funcionalitester`.`Software` (`idSoftware`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionalitester`.`Teste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionalitester`.`Teste` ;

CREATE TABLE IF NOT EXISTS `Funcionalitester`.`Teste` (
  `idTeste` INT NOT NULL AUTO_INCREMENT,
  `Area` VARCHAR(100) NOT NULL,
  `Ocorrencia` VARCHAR(100) NOT NULL,
  `Prioridade` VARCHAR(100) NOT NULL,
  `Tipo` VARCHAR(100) NOT NULL,
  `Situacao` VARCHAR(100) NOT NULL,
  `Observacao` VARCHAR(500) NULL,
  `idDesenvolvedor` INT NULL,
  `EmManutencao` TINYINT NOT NULL,
  `Usuario_Pessoa_idPessoa` INT NOT NULL,
  `Funcionalidade_idFuncionalidade` INT NOT NULL,
  `Software_idSoftware` INT NOT NULL,
  PRIMARY KEY (`idTeste`, `Usuario_Pessoa_idPessoa`, `Funcionalidade_idFuncionalidade`, `Software_idSoftware`),
  INDEX `fk_Teste_Usuario1_idx` (`Usuario_Pessoa_idPessoa` ASC),
  INDEX `fk_Teste_Funcionalidade1_idx` (`Funcionalidade_idFuncionalidade` ASC),
  INDEX `fk_Teste_Software1_idx` (`Software_idSoftware` ASC),
  CONSTRAINT `fk_Teste_Usuario1`
    FOREIGN KEY (`Usuario_Pessoa_idPessoa`)
    REFERENCES `Funcionalitester`.`Usuario` (`Pessoa_idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teste_Funcionalidade1`
    FOREIGN KEY (`Funcionalidade_idFuncionalidade`)
    REFERENCES `Funcionalitester`.`Funcionalidade` (`idFuncionalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teste_Software1`
    FOREIGN KEY (`Software_idSoftware`)
    REFERENCES `Funcionalitester`.`Software` (`idSoftware`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
